import type { Restaurant, MenuItem, MenuCategory, Order, GlobalCategory } from '../types';

export const MOCK_CATEGORIES: GlobalCategory[] = [
  { id: '1', name: 'Oaxaqueña', icon: '🫔', sort_order: 1 },
  { id: '2', name: 'Tacos', icon: '🌮', sort_order: 2 },
  { id: '3', name: 'Mariscos', icon: '🦐', sort_order: 3 },
  { id: '4', name: 'Hamburguesas', icon: '🍔', sort_order: 4 },
  { id: '5', name: 'Pizzas', icon: '🍕', sort_order: 5 },
  { id: '6', name: 'Pollos', icon: '🍗', sort_order: 6 },
  { id: '7', name: 'Sushi', icon: '🍣', sort_order: 7 },
  { id: '8', name: 'Postres', icon: '🍰', sort_order: 8 },
  { id: '9', name: 'Bebidas', icon: '🥤', sort_order: 9 },
  { id: '10', name: 'Desayunos', icon: '🥚', sort_order: 10 },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest_01',
    owner_id: 'usr_rest_01',
    name: 'La Cocina de María',
    description: 'Auténtica comida oaxaqueña hecha con amor. Mole negro, tlayudas y más.',
    address: 'Av. Independencia 234, Centro, Tuxtepec',
    lat: 18.0893,
    lng: -96.1230,
    phone: '+52 287 875 1234',
    rating: 4.8,
    review_count: 342,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '08:00', close: '22:00' }, mar: { open: '08:00', close: '22:00' } },
    delivery_fee: 25,
    minimum_order: 80,
    estimated_time: '25-35 min',
    status: 'abierto',
    categories: ['Oaxaqueña', 'Desayunos'],
    created_at: '2024-01-15',
  },
  {
    id: 'rest_02',
    owner_id: 'usr_rest_02',
    name: 'Burger Craft',
    description: 'Las mejores hamburguesas artesanales de Tuxtepec. Carne Angus 100%.',
    address: 'Blvd. Benito Juárez 567, Col. María Luisa',
    lat: 18.0870,
    lng: -96.1200,
    phone: '+52 287 875 2345',
    rating: 4.6,
    review_count: 218,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '12:00', close: '23:00' } },
    delivery_fee: 30,
    minimum_order: 100,
    estimated_time: '20-30 min',
    status: 'abierto',
    categories: ['Hamburguesas'],
    created_at: '2024-02-20',
  },
  {
    id: 'rest_03',
    owner_id: 'usr_rest_03',
    name: 'Mariscos El Puerto',
    description: 'Pescados y mariscos frescos del Golfo. Cocteles, ceviches y más.',
    address: 'Calle 20 de Noviembre 89, Centro',
    lat: 18.0900,
    lng: -96.1250,
    phone: '+52 287 875 3456',
    rating: 4.7,
    review_count: 189,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '10:00', close: '20:00' } },
    delivery_fee: 35,
    minimum_order: 120,
    estimated_time: '30-40 min',
    status: 'abierto',
    categories: ['Mariscos'],
    created_at: '2024-03-10',
  },
  {
    id: 'rest_04',
    owner_id: 'usr_rest_04',
    name: 'Pizzería Napoli',
    description: 'Pizza artesanal al horno de leña. Masa madre y ingredientes italianos.',
    address: 'Av. Libertad 456, Col. Centro',
    lat: 18.0880,
    lng: -96.1215,
    phone: '+52 287 875 4567',
    rating: 4.5,
    review_count: 156,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '14:00', close: '23:00' } },
    delivery_fee: 20,
    minimum_order: 90,
    estimated_time: '25-35 min',
    status: 'abierto',
    categories: ['Pizzas'],
    created_at: '2024-04-05',
  },
  {
    id: 'rest_05',
    owner_id: 'usr_rest_05',
    name: 'Taquería Don Chava',
    description: 'Tacos al pastor, suadero, bistec y más. Los tacos #1 de Tuxtepec.',
    address: 'Calle Morelos 123, Centro',
    lat: 18.0895,
    lng: -96.1240,
    phone: '+52 287 875 5678',
    rating: 4.9,
    review_count: 521,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '18:00', close: '02:00' } },
    delivery_fee: 15,
    minimum_order: 50,
    estimated_time: '15-25 min',
    status: 'abierto',
    categories: ['Tacos'],
    created_at: '2024-01-05',
  },
  {
    id: 'rest_06',
    owner_id: 'usr_rest_06',
    name: 'Sushi Zen',
    description: 'Sushi fusión con toque mexicano. Rollos especiales y poke bowls.',
    address: 'Blvd. Santos Degollado 789',
    lat: 18.0860,
    lng: -96.1195,
    phone: '+52 287 875 6789',
    rating: 4.4,
    review_count: 98,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '13:00', close: '22:00' } },
    delivery_fee: 40,
    minimum_order: 150,
    estimated_time: '35-45 min',
    status: 'cerrado',
    categories: ['Sushi'],
    created_at: '2024-05-15',
  },
  {
    id: 'rest_07',
    owner_id: 'usr_rest_07',
    name: 'Pollos El Fogón',
    description: 'Pollo asado al carbón con guarniciones. Familiar y económico.',
    address: 'Av. 5 de Mayo 321, Col. Obrera',
    lat: 18.0910,
    lng: -96.1260,
    phone: '+52 287 875 7890',
    rating: 4.3,
    review_count: 267,
    is_approved: true,
    image_url: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '11:00', close: '21:00' } },
    delivery_fee: 20,
    minimum_order: 70,
    estimated_time: '20-30 min',
    status: 'abierto',
    categories: ['Pollos'],
    created_at: '2024-02-28',
  },
  {
    id: 'rest_08',
    owner_id: 'usr_rest_08',
    name: 'Café La Parroquia',
    description: 'Desayunos, café de olla y antojitos oaxaqueños desde temprano.',
    address: 'Portal Juárez 12, Centro',
    lat: 18.0888,
    lng: -96.1228,
    phone: '+52 287 875 8901',
    rating: 4.6,
    review_count: 412,
    is_approved: false,
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    logo_url: null,
    opening_hours: { lun: { open: '06:00', close: '14:00' } },
    delivery_fee: 15,
    minimum_order: 40,
    estimated_time: '15-20 min',
    status: 'abierto',
    categories: ['Desayunos', 'Bebidas'],
    created_at: '2024-06-01',
  },
];

export const MOCK_MENU_CATEGORIES: MenuCategory[] = [
  { id: 'mc_01', restaurant_id: 'rest_01', name: 'Especialidades', sort_order: 1 },
  { id: 'mc_02', restaurant_id: 'rest_01', name: 'Antojitos', sort_order: 2 },
  { id: 'mc_03', restaurant_id: 'rest_01', name: 'Bebidas', sort_order: 3 },
  { id: 'mc_04', restaurant_id: 'rest_02', name: 'Hamburguesas', sort_order: 1 },
  { id: 'mc_05', restaurant_id: 'rest_02', name: 'Complementos', sort_order: 2 },
  { id: 'mc_06', restaurant_id: 'rest_02', name: 'Bebidas', sort_order: 3 },
  { id: 'mc_07', restaurant_id: 'rest_05', name: 'Tacos', sort_order: 1 },
  { id: 'mc_08', restaurant_id: 'rest_05', name: 'Gringas y Quesadillas', sort_order: 2 },
  { id: 'mc_09', restaurant_id: 'rest_03', name: 'Cocteles', sort_order: 1 },
  { id: 'mc_10', restaurant_id: 'rest_03', name: 'Platos Fuertes', sort_order: 2 },
  { id: 'mc_11', restaurant_id: 'rest_04', name: 'Pizzas Clásicas', sort_order: 1 },
  { id: 'mc_12', restaurant_id: 'rest_04', name: 'Pizzas Especiales', sort_order: 2 },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: 'mi_01', restaurant_id: 'rest_01', category_id: 'mc_01', category_name: 'Especialidades',
    name: 'Mole Negro Oaxaqueño', description: 'Pollo bañado en auténtico mole negro con arroz y tortillas hechas a mano.',
    price: 185, image_url: 'https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=400',
    is_available: true, ingredients: ['Pollo', 'Chile mulato', 'Chocolate', 'Tortillas'],
    modifiers: [{ id: 'mod_1', name: 'Proteína', options: [{ label: 'Pollo', price: 0 }, { label: 'Res', price: 30 }] }],
  },
  {
    id: 'mi_02', restaurant_id: 'rest_01', category_id: 'mc_01', category_name: 'Especialidades',
    name: 'Tlayuda Tradicional', description: 'Tortilla gigante crujiente con asiento, frijol, quesillo y tasajo.',
    price: 145, image_url: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=400',
    is_available: true, ingredients: ['Tortilla', 'Asiento', 'Quesillo', 'Tasajo'],
  },
  {
    id: 'mi_03', restaurant_id: 'rest_01', category_id: 'mc_02', category_name: 'Antojitos',
    name: 'Empanadas de Amarillo', description: 'Empanadas de masa rellenas de pollo con mole amarillo.',
    price: 65, image_url: 'https://images.unsplash.com/photo-1609525313344-a56f96ec8a04?w=400',
    is_available: true, ingredients: ['Masa', 'Pollo', 'Mole amarillo'],
  },
  {
    id: 'mi_04', restaurant_id: 'rest_01', category_id: 'mc_03', category_name: 'Bebidas',
    name: 'Agua de Chilacayota', description: 'Refrescante agua fresca de chilacayota con piloncillo.',
    price: 35, image_url: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400',
    is_available: true, ingredients: ['Chilacayota', 'Piloncillo'],
  },
  {
    id: 'mi_05', restaurant_id: 'rest_02', category_id: 'mc_04', category_name: 'Hamburguesas',
    name: 'Angus Clásica', description: 'Carne Angus 200g, queso cheddar, lechuga, tomate y salsa especial.',
    price: 165, image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    is_available: true, ingredients: ['Carne Angus', 'Cheddar', 'Lechuga', 'Tomate'],
    modifiers: [
      { id: 'mod_2', name: 'Extras', options: [{ label: 'Tocino', price: 25 }, { label: 'Doble carne', price: 50 }, { label: 'Aguacate', price: 20 }] },
    ],
  },
  {
    id: 'mi_06', restaurant_id: 'rest_02', category_id: 'mc_04', category_name: 'Hamburguesas',
    name: 'BBQ Bacon', description: 'Carne Angus, tocino crujiente, aros de cebolla y salsa BBQ ahumada.',
    price: 195, image_url: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
    is_available: true, ingredients: ['Carne Angus', 'Tocino', 'Aros de cebolla', 'BBQ'],
  },
  {
    id: 'mi_07', restaurant_id: 'rest_02', category_id: 'mc_05', category_name: 'Complementos',
    name: 'Papas con Queso', description: 'Papas fritas crujientes bañadas en queso cheddar y jalapeño.',
    price: 75, image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
    is_available: true, ingredients: ['Papa', 'Queso cheddar', 'Jalapeño'],
  },
  {
    id: 'mi_08', restaurant_id: 'rest_05', category_id: 'mc_07', category_name: 'Tacos',
    name: 'Tacos al Pastor (5 pzas)', description: 'Cinco tacos de cerdo adobado al trompo con piña y cilantro.',
    price: 85, image_url: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
    is_available: true, ingredients: ['Cerdo', 'Adobo', 'Piña', 'Cilantro'],
  },
  {
    id: 'mi_09', restaurant_id: 'rest_05', category_id: 'mc_07', category_name: 'Tacos',
    name: 'Tacos de Suadero (5 pzas)', description: 'Cinco tacos de suadero crujiente con salsa verde y cebolla.',
    price: 80, image_url: 'https://images.unsplash.com/photo-1624300629298-e9209d3fd1e4?w=400',
    is_available: true, ingredients: ['Suadero', 'Salsa verde', 'Cebolla', 'Cilantro'],
  },
  {
    id: 'mi_10', restaurant_id: 'rest_05', category_id: 'mc_08', category_name: 'Gringas y Quesadillas',
    name: 'Gringa de Pastor', description: 'Tortilla de harina con pastor, queso y piña.',
    price: 55, image_url: 'https://images.unsplash.com/photo-1628191011227-522c7c3f0af5?w=400',
    is_available: true, ingredients: ['Tortilla de harina', 'Pastor', 'Queso', 'Piña'],
  },
  {
    id: 'mi_11', restaurant_id: 'rest_03', category_id: 'mc_09', category_name: 'Cocteles',
    name: 'Coctel de Camarón', description: 'Camarones frescos en salsa de tomate con aguacate y cebolla.',
    price: 165, image_url: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400',
    is_available: true, ingredients: ['Camarón', 'Tomate', 'Aguacate', 'Limón'],
  },
  {
    id: 'mi_12', restaurant_id: 'rest_03', category_id: 'mc_10', category_name: 'Platos Fuertes',
    name: 'Filete de Pescado a la Veracruzana', description: 'Filete fresco en salsa de jitomate con aceitunas y alcaparras.',
    price: 220, image_url: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=400',
    is_available: true, ingredients: ['Pescado', 'Jitomate', 'Aceitunas', 'Alcaparras'],
  },
  {
    id: 'mi_13', restaurant_id: 'rest_04', category_id: 'mc_11', category_name: 'Pizzas Clásicas',
    name: 'Margherita', description: 'Salsa de tomate San Marzano, mozzarella fresca y albahaca.',
    price: 155, image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    is_available: true, ingredients: ['Tomate', 'Mozzarella', 'Albahaca'],
  },
  {
    id: 'mi_14', restaurant_id: 'rest_04', category_id: 'mc_12', category_name: 'Pizzas Especiales',
    name: 'Quattro Formaggi', description: 'Mozzarella, gorgonzola, parmesano y fontina con miel de trufa.',
    price: 210, image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
    is_available: true, ingredients: ['Mozzarella', 'Gorgonzola', 'Parmesano', 'Fontina'],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_01',
    customer_id: 'usr_cliente_01',
    restaurant_id: 'rest_01',
    restaurant_name: 'La Cocina de María',
    restaurant_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    driver_id: 'usr_driver_01',
    driver_name: 'Juan López',
    status: 'entregado',
    items: [
      { id: 'oi_01', menu_item_id: 'mi_01', name: 'Mole Negro Oaxaqueño', quantity: 2, notes: '', price_at_time: 185, modifiers: {} },
      { id: 'oi_02', menu_item_id: 'mi_03', name: 'Empanadas de Amarillo', quantity: 3, notes: 'Sin picante', price_at_time: 65, modifiers: {} },
    ],
    total_amount: 590,
    delivery_fee: 25,
    subtotal: 565,
    address: 'Col. María Luisa, Calle 5 #123',
    lat: 18.0870,
    lng: -96.1200,
    payment_method: 'mercado_pago',
    payment_status: 'pagado',
    notes: '',
    estimated_time: null,
    created_at: '2024-12-15T14:30:00Z',
    updated_at: '2024-12-15T15:15:00Z',
  },
  {
    id: 'ord_02',
    customer_id: 'usr_cliente_01',
    restaurant_id: 'rest_02',
    restaurant_name: 'Burger Craft',
    restaurant_image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800',
    driver_id: 'usr_driver_01',
    driver_name: 'Juan López',
    status: 'preparando',
    items: [
      { id: 'oi_03', menu_item_id: 'mi_05', name: 'Angus Clásica', quantity: 2, notes: 'Sin cebolla', price_at_time: 165, modifiers: {} },
      { id: 'oi_04', menu_item_id: 'mi_07', name: 'Papas con Queso', quantity: 1, notes: '', price_at_time: 75, modifiers: {} },
    ],
    total_amount: 435,
    delivery_fee: 30,
    subtotal: 405,
    address: 'Col. Centro, Av. Independencia #456',
    lat: 18.0893,
    lng: -96.1230,
    payment_method: 'efectivo',
    payment_status: 'pendiente',
    notes: 'Tocar el timbre',
    estimated_time: '25 min',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ord_03',
    customer_id: 'usr_cliente_01',
    restaurant_id: 'rest_05',
    restaurant_name: 'Taquería Don Chava',
    restaurant_image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800',
    driver_id: null,
    driver_name: null,
    status: 'confirmado',
    items: [
      { id: 'oi_05', menu_item_id: 'mi_08', name: 'Tacos al Pastor (5 pzas)', quantity: 2, notes: '', price_at_time: 85, modifiers: {} },
      { id: 'oi_06', menu_item_id: 'mi_10', name: 'Gringa de Pastor', quantity: 2, notes: '', price_at_time: 55, modifiers: {} },
    ],
    total_amount: 295,
    delivery_fee: 15,
    subtotal: 280,
    address: 'Col. Obrera, Calle 10 #789',
    lat: 18.0910,
    lng: -96.1260,
    payment_method: 'mercado_pago',
    payment_status: 'pagado',
    notes: '',
    estimated_time: '20 min',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
